#!/bin/bash

set -Eeo pipefail

AWS_DEFAULT_REGION=eu-west-2
IMAGE_REPO_NAME=deductions/gp-portal
CONTAINER_APP_NAME=portal
NHS_SERVICE=gp-portal

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

# This is where NHS Identity redirects to
PORTAL_DOMAIN_NAME=patient-deductions.nhs.uk

PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function tf_plan {
  operation=$1
  cd terraform

  COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
  IMAGE_TAG=${COMMIT_HASH}

  terraform init -backend-config key=${NHS_SERVICE}-${NHS_ENVIRONMENT}/terraform.tfstate
  terraform get # modules
  if [[ "${operation}" == "create" ]]; then
    terraform plan -var task_image_tag=$IMAGE_TAG -var-file=$NHS_ENVIRONMENT.tfvars -out="nhs_deployment.tfplan"
  elif [[ "${operation}" == "destroy" ]]; then
    terraform plan -var task_image_tag=$IMAGE_TAG -var-file=$NHS_ENVIRONMENT.tfvars -out="nhs_deployment.tfplan" -destroy
  else
    echo "Unknown operation (should be create or destroy), got: ${operation}"
    exit 1
  fi
}

function tf_apply {
  cd terraform
  terraform init -backend-config key=${NHS_SERVICE}-${NHS_ENVIRONMENT}/terraform.tfstate
  terraform get # modules
  terraform apply nhs_deployment.tfplan
  terraform output -json > tf-out.json
}

function docker_login {
  echo Logging in to Amazon ECR...
  eval $(dojo -c Dojofile-infra "aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION")
}

function get_aws_secret {
  secret_id=$1
  json=$(aws ssm get-parameter --with-decryption --region $AWS_DEFAULT_REGION --name $secret_id)
  if [ $? != 0 ]; then
    >&2 echo "Failed to obtain AWS secret: $secret_id"
    exit 5
  fi
  echo $json | jq -r ".Parameter.Value"
}

function generate_certs {
  if [ ! -f ${PORTAL_DOMAIN_NAME}.key ]; then
    rm -rf prm-deductions-support-infra
    git clone https://github.com/nhsconnect/prm-deductions-support-infra.git
    cd prm-deductions-support-infra
    dojo "./utils/generate-certs.sh -f ${PORTAL_DOMAIN_NAME} -d ${PORTAL_DOMAIN_NAME}"
    cd ..
    cp ./prm-deductions-support-infra/utils/site-certs/${PORTAL_DOMAIN_NAME}* ./
  else
    echo "certificates already exist"
  fi
}

command="$1"
case "${command}" in
  start_proxy)
      export PORTAL_DOMAIN_NAME
      generate_certs
      sed "s/PORTAL_DOMAIN_NAME/${PORTAL_DOMAIN_NAME}/g" proxy.conf.tmpl > proxy.conf
      docker-compose up -d
      ;;
  stop_proxy)
      docker-compose down
      ;;
  _dep)
      echo "Running NPM Audit ..."
      npm audit --audit-level=moderate
      ;;
  dep)
      dojo "./tasks _dep"
      ;;
  _install)
      npm install
      ;;
  install)
      dojo "./tasks _install"
      ;;
  _build)
      rm -rf build/*
      npm install
      npm rebuild node-sass # Added to fix an issue with library bindings with OS X vs Linux
      npm run build
      # Remove symlink to missing file
      rm -f build/favicon.ico
      ;;
  build)
      dojo "./tasks _build"
      ;;
  generate_certs)
      generate_certs
      ;;
  _test)
      npm install
      npm run test
      ;;
  test)
      ./tasks generate_certs
      dojo "./tasks _test"
      ;;
  _coverage)
      npm install
      npm run coverage
      ;;
  coverage)
      ./tasks generate_certs
      dojo "./tasks _coverage"
      ;;
  _access_test)
      npm install
      npm rebuild node-sass
      npm run access
      ;;
  access_test)
      dojo "./tasks _access_test"
      ;;
  build_docker_local)
      REPOSITORY_URI=$IMAGE_REPO_NAME
      COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
      IMAGE_TAG=${COMMIT_HASH}
      echo Build started on `date`
      echo Building the Docker image...
      docker build -t $REPOSITORY_URI:latest .
      docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      echo Build completed on `date`
      ;;
  run_react_local)
      npm install
      npm rebuild node-sass
      echo Launching React app...
      npm run start:react
      ;;
  run_server_local)
      npm install
      npm rebuild node-sass
      echo Launching Express server...
      npm run start:server
      ;;
  build_docker)
      docker_login
      AWS_ACCOUNT_ID=$(dojo -c Dojofile-infra "aws sts get-caller-identity | jq -r .Account")
      REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$IMAGE_REPO_NAME
      ./tasks build_docker_local
      COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
      IMAGE_TAG=${COMMIT_HASH}
      docker tag $IMAGE_REPO_NAME $REPOSITORY_URI:$IMAGE_TAG
      docker tag $IMAGE_REPO_NAME $REPOSITORY_URI:latest
      echo "Pushing the Docker image...
      $REPOSITORY_URI:latest
      $REPOSITORY_URI:$IMAGE_TAG"
      docker push $REPOSITORY_URI:latest
      docker push $REPOSITORY_URI:$IMAGE_TAG
      ;;
  _test_docker)
      while ! curl -i ${PORTAL_URL}; do
        echo "Waiting for portal server endpoint at ${PORTAL_URL}"
        sleep 1
        ((count++))
        if [ 30 -le $count ]; then
          echo "Timed-out waiting for portal server at ${PORTAL_URL}"
          exit 5
        fi
      done
      ;;
  test_docker_local)
      export PORTAL_URL="http://${PORTAL_DOMAIN_NAME}:3000"
      export PORTAL_DOCKER_IMAGE="${PORTAL_DOCKER_IMAGE:-$IMAGE_REPO_NAME}"
      dojo -c Dojofile-dtest "./tasks _test_docker"
      ;;
  run_docker_local)
      ./tasks generate_certs
      export PORTAL_URL="https://${PORTAL_DOMAIN_NAME}"
      export USE_HTTP="false"
      export PORTAL_DOCKER_IMAGE="${PORTAL_DOCKER_IMAGE:-$IMAGE_REPO_NAME}"
      dojo -c Dojofile-demo bash
      ;;
  test_docker)
      # Tests that image uses variables for config and runs migration on start
      docker_login
      COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
      IMAGE_TAG=${COMMIT_HASH}
      AWS_ACCOUNT_ID=$(dojo -c Dojofile-infra "aws sts get-caller-identity | jq -r .Account")
      REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      export PORTAL_DOCKER_IMAGE="${REPOSITORY_URI}/$IMAGE_REPO_NAME:${IMAGE_TAG}"
      ./tasks test_docker_local
      ;;
  tf)
      check_env
      dojo -c Dojofile-infra "bash"
      ;;
  _tf_plan)
      tf_plan "$2"
      ;;
  tf_plan)
      check_env
      dojo -c Dojofile-infra "./tasks _tf_plan $2"
      ;;
  _tf_apply)
      tf_apply
      ;;
  tf_apply)
      check_env
      dojo -c Dojofile-infra "./tasks _tf_apply"
      ;;
  _wait_ecs)
      aws ecs wait services-stable \
        --region $AWS_DEFAULT_REGION \
        --cluster $NHS_ENVIRONMENT-deductions-public-ecs-cluster \
        --services $NHS_ENVIRONMENT-gp-practice-portal-service
      ;;
  wait_ecs)
      check_env
      dojo -c Dojofile-infra "./tasks _wait_ecs"
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
