format_version: 4
pipelines:
  "prm-deductions-portal-gp-practice":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - build:
          clean_workspace: true
          jobs:
            dependency_check:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dep
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test
            coverage:
              artifacts:
                - build:
                    source: coverage/lcov-report
              tabs:
                coverage: lcov-report/index.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks coverage
            access_test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks access_test
            npm_install:
              resources:
                - docker
              artifacts:
                - build:
                    source: build
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build
      - docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: npm_install
                    source: build
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker
      - test_docker:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_docker

  "prm-deductions-portal-gp-practice.dev":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
      app:
        pipeline: prm-deductions-portal-gp-practice
        stage: test_docker
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks tf_plan create
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks tf_apply
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks wait_ecs
